### ISSUE TITLE
Do we need a further repo?

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/pineline#1]
Hello @NNPDF/theory (I added all people involved to the team, to mention all at once).

I created a new repository to host ~~a logo~~ documentation (the logo is just candidate, if you have opinions let's open a dedicated discussion).

I'd like to answer the question in the title, so I will consider both the answers:
- **no**: one repo more is by default worse then one repo less, in terms of maintenance and focus, and we already had `fktables` (now archived) and Pineko, that is the final driver for FkTables creation, so we could use that one
- **yes**: the full theory *pineline* is more then whatever Pineko will be, since the goal of Pineko is strictly to create FkTables, but there are two other ingredients, i.e. *runcards* (eventually connected to Commondata) and *runcardsrunner* (that is currently interfacing the actual generators, and streamlining grids production)

Since Pineko will rely on computed grids, I thought that we need a further place to document (even briefly) the overall ecosystem, including things like the Snowmass diagram, and all the pointers to the repo and tools that are involved in this.

The other option would be to use nnpdf main repository and documentation. But one of the goals of the new pineline would be not to be strictly coupled to NNPDF (even though it's clear that the project is born under the aegis of the collaboration, simply can be used even outside), so maybe having dedicated docs is not a bad idea.

However, I'll start collecting material while I produce it, but if your feedback is negative we can decide to move it somewhere else :)

**Comment by felixhekhorn** [comment]
by now the de-facto answer is: yes
